#!/usr/bin/env python3
"""
Stage 4: emit the concatenated AICA-ADPCM sample pool (binary) + a generated-C
descriptor side-table.

Outputs (aicaseq/out/):
  adpcm_pool.bin        - all samples' AICA ADPCM, each 32-byte aligned
  aica_sample_table.h   - struct + extern decls
  aica_sample_table.c   - the descriptor array, sorted by src_offset (binary-searchable)

Lookup key `src_offset` = global Audiotable byte offset (bank rom_addr + sampleAddr).
Runtime derives it as (sample->sampleAddr - gAudiotableBase). Confirm in Stage 5.
"""

import os
from multiprocessing import Pool
from pathlib import Path

from audiobank_parse import parse_all
from transcode import transcode_sample, FORCE_PCM_KEYS, FMT_PCM16, FMT_PCM8, FMT_ADPCM

ALIGN = 32


def align_up(n, a):
    return (n + a - 1) & ~(a - 1)


def _transcode_one(item):
    """Pool worker: (Sample, src_offset, bank, addr) -> descriptor (pool_offset later).
    force-PCM is decided here because src_offset (the runtime key) needs the bank base."""
    s, src_offset, bank, addr = item
    d = transcode_sample(s, force=(src_offset in FORCE_PCM_KEYS))
    d["src_offset"] = src_offset
    d["bank"] = bank
    d["addr"] = addr
    return d


def main(audiobank, audiotable, tables_json, outdir, incdir, pool_path):
    outdir = Path(outdir)
    incdir = Path(incdir)
    pool_path = Path(pool_path)
    tables, samples = parse_all(audiobank, audiotable, tables_json, with_data=True)
    bank_base = {b["index"]: b["rom_addr"] for b in tables["sample_banks"] if not b["is_ptr"]}

    # Per-sample transcode (beam search) is independent and CPU-heavy -> fan out
    # across cores. Pool.map preserves order; offsets/keys are assigned serially
    # afterward and we re-sort by src_offset, so output is deterministic.
    items = [(s, bank_base[bank] + addr, bank, addr)
             for (bank, addr), s in samples.items()]
    with Pool(os.cpu_count()) as pool:
        descs = pool.map(_transcode_one, items)

    blob = bytearray()
    for d in descs:
        d["pool_offset"] = len(blob)
        blob += d["data"]
        blob += b"\x00" * (align_up(len(blob), ALIGN) - len(blob))

    descs.sort(key=lambda d: d["src_offset"])

    # --- integrity checks ---
    keys = [d["src_offset"] for d in descs]
    assert keys == sorted(keys) and len(keys) == len(set(keys)), "keys not sorted/unique"
    for d in descs:
        assert d["pool_offset"] + len(d["data"]) <= len(blob)
        assert blob[d["pool_offset"]:d["pool_offset"] + len(d["data"])] == d["data"]
        assert d["nsamples"] <= 65534
        assert 0 <= d["loop_start"] <= d["loop_end"] <= d["nsamples"]
        assert d["downsample_shift"] in (0, 1)
    print(f"integrity OK: {len(descs)} descriptors, keys unique+sorted, pool slices match")

    outdir.mkdir(parents=True, exist_ok=True)
    incdir.mkdir(parents=True, exist_ok=True)
    pool_path.parent.mkdir(parents=True, exist_ok=True)
    pool_path.write_bytes(blob)

    # --- header ---
    h = []
    h.append("/* Auto-generated by tools/aica/emit_table.py. Do not edit. */")
    h.append("#ifndef AICA_SAMPLE_TABLE_H")
    h.append("#define AICA_SAMPLE_TABLE_H")
    h.append("#include <stdint.h>")
    h.append("")
    h.append("typedef struct {")
    h.append("    uint32_t src_offset;       /* global Audiotable offset (lookup key) */")
    h.append("    uint32_t pool_offset;      /* byte offset into adpcm_pool.bin */")
    h.append("    uint32_t byte_len;         /* AICA-ADPCM byte length */")
    h.append("    uint16_t nsamples;         /* sample count (<=65534) */")
    h.append("    uint16_t loop_start;       /* in samples */")
    h.append("    uint16_t loop_end;         /* in samples (= nsamples for one-shot) */")
    h.append("    uint8_t  loop_flag;        /* 1 = looping */")
    h.append("    uint8_t  downsample_shift; /* 0, or 1 = 2x-decimated, play at freq>>1 */")
    h.append("    uint8_t  fmt;              /* AICA_SM_* format: 0=PCM16 1=PCM8 2=ADPCM */")
    h.append("} AicaSampleDesc;")
    h.append("")
    h.append(f"#define AICA_SAMPLE_COUNT {len(descs)}")
    h.append(f"#define AICA_ADPCM_POOL_SIZE {len(blob)}u")
    h.append("extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];")
    h.append("")
    h.append("#endif")
    (incdir / "aica_sample_table.h").write_text("\n".join(h) + "\n")

    # --- source ---
    c = []
    c.append("/* Auto-generated by tools/aica/emit_table.py. Do not edit. */")
    c.append('#include "aica_sample_table.h"')
    c.append("")
    c.append("const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT] = {")
    for d in descs:
        c.append(
            f"    {{ 0x{d['src_offset']:06X}, 0x{d['pool_offset']:06X}, {len(d['data']):>6}, "
            f"{d['nsamples']:>5}, {d['loop_start']:>5}, {d['loop_end']:>5}, "
            f"{1 if d['loop'] else 0}, {d['downsample_shift']}, {d['fmt']} }}, "
            f"/* bank{d['bank']} +0x{d['addr']:X} */"
        )
    c.append("};")
    (outdir / "aica_sample_table.c").write_text("\n".join(c) + "\n")

    n16 = sum(1 for d in descs if d["fmt"] == FMT_PCM16)
    n8 = sum(1 for d in descs if d["fmt"] == FMT_PCM8)
    nad = sum(1 for d in descs if d["fmt"] == FMT_ADPCM)
    from transcode import _HAVE_SCIPY
    print(f"emit_table: {len(descs)} descs  ADPCM={nad} PCM16={n16} PCM8={n8}, "
          f"pool {len(blob):,} B -> {pool_path}, "
          f"table -> {outdir}/{incdir}{'' if _HAVE_SCIPY else '  [stdlib decimate fallback]'}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--audiobank", required=True)
    ap.add_argument("--audiotable", required=True)
    ap.add_argument("--tables", required=True, help="audio_tables.json")
    ap.add_argument("--outdir", required=True, help="dir for aica_sample_table.c")
    ap.add_argument("--incdir", help="dir for aica_sample_table.h (default: outdir)")
    ap.add_argument("--pool", required=True, help="output path for adpcm_pool.bin")
    a = ap.parse_args()
    main(a.audiobank, a.audiotable, a.tables, a.outdir, a.incdir or a.outdir, a.pool)
