/* Auto-generated by tools/aica/emit_table.py. Do not edit. */
#ifndef AICA_SAMPLE_TABLE_H
#define AICA_SAMPLE_TABLE_H
#include <stdint.h>

typedef struct {
    uint32_t src_offset;       /* global Audiotable offset (lookup key) */
    uint32_t pool_offset;      /* byte offset into adpcm_pool.bin */
    uint32_t byte_len;         /* AICA-ADPCM byte length */
    uint16_t nsamples;         /* sample count (<=65534) */
    uint16_t loop_start;       /* in samples */
    uint16_t loop_end;         /* in samples (= nsamples for one-shot) */
    uint8_t  loop_flag;        /* 1 = looping */
    uint8_t  downsample_shift; /* 0, or 1 = 2x-decimated, play at freq>>1 */
    uint8_t  fmt;              /* AICA_SM_* format: 0=PCM16 1=PCM8 2=ADPCM */
} AicaSampleDesc;

#define AICA_SAMPLE_COUNT 449
#define AICA_ADPCM_POOL_SIZE 4386464u
extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];

#endif
