/*
 * AICA hardware-mixed voice driver (Dreamcast).
 *
 * Replaces the SH4 software synthesis/mixer. Each audio frame, after the
 * sequence/note tick has finalized the NoteSubEu set, we walk the active notes
 * and drive AICA hardware channels (key-on / live update / key-off) through the
 * KOS SH4->AICA command queue. Samples live as AICA Yamaha-ADPCM in the resident
 * adpcm_pool (offline-transcoded); we stage them into AICA sound RAM (ARAM) on
 * demand via a small refcounted cache. Synthetic wavetables are uploaded to ARAM
 * once at init and played as ordinary looped 16-bit voices.
 *
 * Cooperates with stock KOS firmware only (no custom ARM code); the only
 * non-public KOS dependency is snd_sh4_to_aica (declared extern below), used to
 * issue live channel UPDATE commands that KOS exposes no API for.
 */

#include "ultra64.h"
#include "audio.h"
#include "aica_synth.h"

#ifdef __DREAMCAST__

#include <dc/sound/sound.h>      /* snd_mem_malloc / snd_mem_free */
#include <dc/spu.h>              /* spu_memload_sq */
#include <dc/sound/aica_comm.h>  /* AICA_CMDSTR_CHANNEL, AICA_CMD_CHAN, AICA_CH_CMD_* */
#include <stdio.h>

#define AICA_OCTAVE_LOG 0   /* log ADPCM samples pitched past +1 octave -> FORCE_PCM candidates */

/* Internal KOS symbol: enqueue a packet to the AICA. Not in public headers. */
extern int snd_sh4_to_aica(void* packet, uint32_t size);

/* Generated by aicaseq/tools/emit_table.py (compiled into the build). */
#include "aica_sample_table.h"

/* Set by the asset loader once adpcm_pool.bin is resident. */
const unsigned char* gAicaAdpcmPoolBase = NULL;

/* VROM base of the Audiotable segment; sample->sampleAddr - this = src_offset key. */
/* The Audiotable's VROM start, from the linker symbol so the sample-lookup key
   tracks the real layout. This was a hardcoded 0x94860 (the rebuilt N64 map's
   value); the MIPS-free asset packer (option A) places Audiotable at the
   baserom's 0x94870, so every key came out +0x10 and every sample_lookup
   silently missed -> all sampled voices dead, synth voices unaffected. */
extern u8 _AudiotableSegmentRomStart[];
#define AUDIOTABLE_VROM_BASE ((u32)_AudiotableSegmentRomStart)

#define NUM_AICA_CHANNELS 64
#define MAX_VOICES 64            /* must be >= gAudioCtx.numNotes */
#define ARAM_CACHE_ENTRIES 192
#define AICA_LEN_MAX 65534

/* Synthetic waves are full-scale; two same-waveform voices summing on the AICA
   mix bus clip (no HW overflow protection). Attenuate synth voices for headroom.
   Out of 256 (256 = unity); tune on HW -- lower if crunchy, raise if too quiet. */
#define SYNTH_VOL_SCALE 192

/* ---- ARAM sample cache (refcounted, lazy LRU eviction) ---- */

typedef struct {
    u32 key;        /* src_offset; KEY_EMPTY when unused */
    u32 aram;       /* ARAM address of staged ADPCM, 0 if none */
    u32 len;        /* byte length */
    s32 refs;       /* active voices referencing it */
    u32 lru;        /* tick of last (re)use */
} AramEntry;

#define KEY_EMPTY 0xFFFFFFFFu

static AramEntry sCache[ARAM_CACHE_ENTRIES];
static u32 sTick;

/* ---- channel allocation ---- */

static s8 sChanFree[NUM_AICA_CHANNELS];
static s32 sChanFreeTop;

/* ---- per-note voice tracking ---- */

typedef struct {
    s8 channel;     /* -1 = none */
    u8 active;
    u32 sampleKey;  /* current resolved key (src_offset, or synthetic-encoded) */
    AramEntry* entry; /* cache entry held (refcounted), NULL for synthetic */
    u8 downsampleShift; /* res.downsample_shift of the loaded sample (sub-tick calc_freq) */
    u32 sentFreq;       /* last freq/vol/pan pushed; gates redundant sub-tick updates */
    u8 sentVol, sentPan;
} Voice;

static Voice sVoices[MAX_VOICES];

/* ---- synthetic wavetables, uploaded resident at init ---- */

#define NUM_WAVEFORMS 5          /* saw, tri, sine, square, noise */
#define NUM_HARMONICS 4          /* sNumSamplesPerWavePeriod has 4 entries */
static u32 sWaveAram[NUM_WAVEFORMS][NUM_HARMONICS];

/* Synthetic key space sits above the Audiotable range so it never collides
   with a real src_offset. */
#define SYNTH_KEY(wf, h) (0x80000000u | ((u32)(wf) << 4) | (u32)(h))

/* ---- resolved-sample descriptor passed to the channel command builder ---- */

typedef struct {
    u32 base;       /* ARAM address */
    u32 type;       /* AICA_SM_ADPCM / AICA_SM_16BIT */
    u32 length;     /* samples */
    u32 loop;       /* 0/1 */
    u32 loopstart;
    u32 loopend;
    u8 downsample_shift;
} Resolved;

/* ------------------------------------------------------------------ */

static int sample_lookup(u32 key, const AicaSampleDesc** out) {
    /* binary search gAicaSampleTable (sorted by src_offset) */
    s32 lo = 0, hi = AICA_SAMPLE_COUNT - 1;
    while (lo <= hi) {
        s32 mid = (lo + hi) >> 1;
        u32 k = gAicaSampleTable[mid].src_offset;
        if (k == key) { *out = &gAicaSampleTable[mid]; return 1; }
        if (k < key) lo = mid + 1; else hi = mid - 1;
    }
    return 0;
}

static AramEntry* cache_find(u32 key) {
    for (s32 i = 0; i < ARAM_CACHE_ENTRIES; i++) {
        if (sCache[i].key == key) return &sCache[i];
    }
    return NULL;
}

/* Capped, greppable diagnostics for the otherwise-silent sample-voice bail-outs
   (grep the serial log for "AICA_SKIP:"). Capped so a systematic failure can't
   flood the console. */
static u32 sSkipLogged;
#define AICA_SKIP_LOG(...) \
    do { if (sSkipLogged < 48) { sSkipLogged++; printf("AICA_SKIP: " __VA_ARGS__); } } while (0)

/* Stage a sample's ADPCM into ARAM, returning its cache entry (refs already
   incremented), or NULL on failure. */
static AramEntry* cache_acquire(u32 key, u32 pool_offset, u32 byte_len) {
    AramEntry* e = cache_find(key);
    if (e != NULL) {
        e->refs++;
        e->lru = sTick;
        return e;
    }

    u32 aram = (u32)snd_mem_malloc(byte_len);
    if (aram == 0) {
        /* ARAM full: evict the least-recently-used unreferenced entry, retry. */
        AramEntry* victim = NULL;
        for (s32 i = 0; i < ARAM_CACHE_ENTRIES; i++) {
            if (sCache[i].key != KEY_EMPTY && sCache[i].refs == 0) {
                if (victim == NULL || sCache[i].lru < victim->lru) victim = &sCache[i];
            }
        }
        if (victim != NULL) {
            snd_mem_free(victim->aram);
            victim->key = KEY_EMPTY;
            victim->aram = 0;
            aram = (u32)snd_mem_malloc(byte_len);
        }
        if (aram == 0) {
            AICA_SKIP_LOG("ARAM alloc fail key=%08X len=%u\n", (unsigned)key, (unsigned)byte_len);
            return NULL;
        }
    }

    /* upload ADPCM bytes from the resident pool to ARAM */
    spu_memload_sq(aram, (void*)(gAicaAdpcmPoolBase + pool_offset), (byte_len + 31) & ~31);

    /* find a free slot */
    e = cache_find(KEY_EMPTY);
    if (e == NULL) {
        /* table full of resident entries — shouldn't happen with eviction above */
        AICA_SKIP_LOG("cache table full key=%08X\n", (unsigned)key);
        snd_mem_free(aram);
        return NULL;
    }
    e->key = key;
    e->aram = aram;
    e->len = byte_len;
    e->refs = 1;
    e->lru = sTick;
    return e;
}

static void cache_release(AramEntry* e) {
    if (e != NULL && e->refs > 0) e->refs--;
}

/* ------------------------------------------------------------------ */

/* AICA freq in Hz from the note's resampling rate.
   resamplingRateFixedPoint = rate * 32768; true rate doubles when hasTwoParts
   (software-resampler split); play decimated samples at half freq. */
static u32 calc_freq(NoteSubEu* sub, u8 downsample_shift) {
    u32 rateFixed = sub->resamplingRateFixedPoint;
    u32 freq = ((u32)rateFixed * 32000u) >> 15;   /* rate * 32000 */
    if (sub->bitField1.hasTwoParts) freq <<= 1;
    freq >>= downsample_shift;
    if (freq == 0) freq = 1;
    return freq;
}

/* targetVolLeft/Right are ~0..0x1000 gains. AICA vol is 0..255 linear
   (firmware applies the log curve). */
static u32 calc_vol(NoteSubEu* sub) {
    u32 l = sub->targetVolLeft, r = sub->targetVolRight;
    u32 m = (l > r) ? l : r;
    u32 v = m >> 4;                 /* 0x1000 -> 0x100 */
    if (v > 255) v = 255;
    /* Headroom for full-scale synth waves summing without clipping (see above). */
    if (sub->bitField1.isSyntheticWave) v = (v * SYNTH_VOL_SCALE) >> 8;
    return v;
}

/* AICA pan: 0=left, 128=center, 255=right. Approximate from the L/R balance. */
static u32 calc_pan(NoteSubEu* sub) {
    s32 l = sub->targetVolLeft, r = sub->targetVolRight;
    s32 sum = l + r;
    if (sum == 0) return 128;
    s32 pan = 128 + (127 * (r - l)) / sum;
    if (pan < 0) pan = 0;
    if (pan > 255) pan = 255;
    return (u32)pan;
}

/* Resolve a note's sample (real or synthetic) into ARAM playback parameters,
   acquiring a cache entry if needed. Returns 1 on success. */
static int resolve(NoteSubEu* sub, u32* outKey, Resolved* res, AramEntry** outEntry) {
    *outEntry = NULL;

    res->downsample_shift = 0;

    if (sub->bitField1.isSyntheticWave) {
        /* waveSampleAddr = &gWaveSamples[waveId-128][harmonic*WAVE_SAMPLE_COUNT].
           Both the waveform AND the harmonic are encoded in the pointer itself:
           find the waveform by range, then the harmonic from the element offset.
           (Do NOT use harmonicIndexCurAndPrev — func_800DB03C zeroes it each tick.) */
        extern s16* gWaveSamples[];
        s32 wf = -1;
        u32 h = 0;
        for (u32 w = 0; w < NUM_WAVEFORMS; w++) {
            if (sub->waveSampleAddr >= gWaveSamples[w] &&
                sub->waveSampleAddr < gWaveSamples[w] + NUM_HARMONICS * WAVE_SAMPLE_COUNT) {
                wf = (s32)w;
                h = (u32)(sub->waveSampleAddr - gWaveSamples[w]) / WAVE_SAMPLE_COUNT;
                break;
            }
        }
        if (wf < 0) return 0;                 /* unknown wave (e.g. gWaveSamples[8]) */
        if (h >= NUM_HARMONICS) h = NUM_HARMONICS - 1;
        *outKey = SYNTH_KEY(wf, h);
        res->base = sWaveAram[wf][h];
        res->type = AICA_SM_16BIT;
        res->length = WAVE_SAMPLE_COUNT;
        res->loop = 1;
        res->loopstart = 0;
        res->loopend = WAVE_SAMPLE_COUNT;
        return 1;
    }

    /* real sample */
    if (gAicaAdpcmPoolBase == NULL) { AICA_SKIP_LOG("pool not resident\n"); return 0; }
    if (sub->tunedSample == NULL || sub->tunedSample->sample == NULL) {
        AICA_SKIP_LOG("no tunedSample\n");
        return 0;
    }
    {
        Sample* s = sub->tunedSample->sample;
        u32 key = (u32)s->sampleAddr - AUDIOTABLE_VROM_BASE;
        const AicaSampleDesc* d;
        if (!sample_lookup(key, &d)) {
            /* the key MUST equal an offline src_offset; print both inputs so an
               off-by-N base mismatch is obvious in the serial log */
            AICA_SKIP_LOG("lookup MISS key=%08X sampleAddr=%08X base=%08X\n",
                          (unsigned)key, (unsigned)(uintptr_t)s->sampleAddr,
                          (unsigned)AUDIOTABLE_VROM_BASE);
            return 0;
        }

        AramEntry* e = cache_acquire(key, d->pool_offset, d->byte_len);
        if (e == NULL) {
            AICA_SKIP_LOG("acquire fail key=%08X pool_off=%08X len=%u\n",
                          (unsigned)key, (unsigned)d->pool_offset, (unsigned)d->byte_len);
            return 0;
        }

        *outEntry = e;
        *outKey = key;
        res->base = e->aram;
        res->type = d->fmt;   /* AICA_SM_16BIT/8BIT/ADPCM, chosen offline by SNR/octave */
        res->length = d->nsamples > AICA_LEN_MAX ? AICA_LEN_MAX : d->nsamples;
        res->loop = d->loop_flag;
        res->loopstart = d->loop_start;
        res->loopend = d->loop_end ? d->loop_end : res->length;
        res->downsample_shift = d->downsample_shift;
        return 1;
    }
}

/* ---- channel commands ---- */

static void chan_start(s32 ch, const Resolved* r, u32 freq, u32 vol, u32 pan) {
    AICA_CMDSTR_CHANNEL(tmp, cmd, chan);
    cmd->cmd = AICA_CMD_CHAN;
    cmd->timestamp = 0;
    cmd->size = AICA_CMDSTR_CHANNEL_SIZE;
    cmd->cmd_id = ch;
    chan->cmd = AICA_CH_CMD_START;
    chan->base = r->base;
    chan->type = r->type;
    chan->length = r->length;
    chan->loop = r->loop;
    chan->loopstart = r->loopstart;
    chan->loopend = r->loopend;
    chan->freq = freq;
    chan->vol = vol;
    chan->pan = pan;
    snd_sh4_to_aica(tmp, cmd->size);
}

static void chan_update(s32 ch, u32 freq, u32 vol, u32 pan) {
    AICA_CMDSTR_CHANNEL(tmp, cmd, chan);
    cmd->cmd = AICA_CMD_CHAN;
    cmd->timestamp = 0;
    cmd->size = AICA_CMDSTR_CHANNEL_SIZE;
    cmd->cmd_id = ch;
    chan->cmd = AICA_CH_CMD_UPDATE | AICA_CH_UPDATE_SET_FREQ | AICA_CH_UPDATE_SET_VOL |
                AICA_CH_UPDATE_SET_PAN;
    chan->freq = freq;
    chan->vol = vol;
    chan->pan = pan;
    snd_sh4_to_aica(tmp, cmd->size);
}

static void chan_stop(s32 ch) {
    AICA_CMDSTR_CHANNEL(tmp, cmd, chan);
    cmd->cmd = AICA_CMD_CHAN;
    cmd->timestamp = 0;
    cmd->size = AICA_CMDSTR_CHANNEL_SIZE;
    cmd->cmd_id = ch;
    chan->cmd = AICA_CH_CMD_STOP;
    snd_sh4_to_aica(tmp, cmd->size);
}

static s32 chan_alloc(void) {
    if (sChanFreeTop == 0) return -1;
    return sChanFree[--sChanFreeTop];
}

static void chan_release(s32 ch) {
    if (sChanFreeTop < NUM_AICA_CHANNELS) sChanFree[sChanFreeTop++] = (s8)ch;
}

static void voice_stop(s32 i) {
    Voice* v = &sVoices[i];
    if (v->channel >= 0) {
        chan_stop(v->channel);
        chan_release(v->channel);
    }
    cache_release(v->entry);
    v->channel = -1;
    v->active = 0;
    v->entry = NULL;
    v->sampleKey = KEY_EMPTY;
    v->downsampleShift = 0;
    v->sentFreq = 0;
    v->sentVol = 0;
    v->sentPan = 0;
}

/* ------------------------------------------------------------------ */

void AicaSynth_Init(void) {
    extern s16* gWaveSamples[];

    for (s32 i = 0; i < ARAM_CACHE_ENTRIES; i++) {
        sCache[i].key = KEY_EMPTY;
        sCache[i].aram = 0;
        sCache[i].refs = 0;
    }
    for (s32 i = 0; i < MAX_VOICES; i++) {
        sVoices[i].channel = -1;
        sVoices[i].active = 0;
        sVoices[i].entry = NULL;
        sVoices[i].sampleKey = KEY_EMPTY;
        sVoices[i].downsampleShift = 0;
        sVoices[i].sentFreq = 0;
        sVoices[i].sentVol = 0;
        sVoices[i].sentPan = 0;
    }
    sChanFreeTop = 0;
    for (s32 ch = NUM_AICA_CHANNELS - 1; ch >= 0; ch--) {
        sChanFree[sChanFreeTop++] = (s8)ch;
    }

    /* Upload synthetic wavetables to ARAM as resident 16-bit PCM. Each waveform
       holds NUM_HARMONICS * WAVE_SAMPLE_COUNT s16; play loop is one harmonic's
       WAVE_SAMPLE_COUNT samples. */
    for (u32 w = 0; w < NUM_WAVEFORMS; w++) {
        u32 bytes = NUM_HARMONICS * WAVE_SAMPLE_COUNT * sizeof(s16);
        u32 aram = (u32)snd_mem_malloc(bytes);
        spu_memload_sq(aram, (void*)gWaveSamples[w], (bytes + 31) & ~31);
        for (u32 h = 0; h < NUM_HARMONICS; h++) {
            sWaveAram[w][h] = aram + h * WAVE_SAMPLE_COUNT * sizeof(s16);
        }
    }
}

/* Re-push freq/vol/pan for active voices at sub-tick `tick` (0..ticksPerUpdate-1),
   reading that tick's noteSubsEu slice, so fast pan/tremolo/vibrato keep the
   sub-frame resolution the chunked RSP render had instead of being snapped to the
   last tick once per frame (AicaSynth_Update). Lifecycle (start/stop/retrigger)
   stays in AicaSynth_Update. Gated on change so static notes add no traffic. Safe
   before init: all voices are zero-initialized (active=0), so this no-ops until
   AicaSynth_Update has started voices. */
void AicaSynth_RefreshActive(s32 tick) {
    s32 numNotes = gAudioCtx.numNotes;
    s32 base = tick * numNotes;

    if (numNotes > MAX_VOICES) numNotes = MAX_VOICES;

    for (s32 i = 0; i < numNotes; i++) {
        Voice* v = &sVoices[i];
        NoteSubEu* sub = &gAudioCtx.noteSubsEu[base + i];
        u32 freq, vol, pan;

        if (!v->active || v->channel < 0) continue;
        if (!sub->bitField0.enabled) continue;   /* AicaSynth_Update will stop it */

        freq = calc_freq(sub, v->downsampleShift);
        vol = calc_vol(sub);
        pan = calc_pan(sub);
        if (freq != v->sentFreq || (u8)vol != v->sentVol || (u8)pan != v->sentPan) {
            chan_update(v->channel, freq, vol, pan);
            v->sentFreq = freq; v->sentVol = (u8)vol; v->sentPan = (u8)pan;
        }
    }
}

void AicaSynth_Update(void) {
    static int sInited = 0;
    s32 stride = gAudioCtx.numNotes;   /* noteSubsEu row stride = full note count */
    s32 ticks = gAudioCtx.audioBufferParameters.ticksPerUpdate;
    s32 numNotes = stride;

    if (!sInited) {
        AicaSynth_Init();
        sInited = 1;
    }

    sTick++;

    if (numNotes > MAX_VOICES) numNotes = MAX_VOICES;

    for (s32 i = 0; i < numNotes; i++) {
        Voice* v = &sVoices[i];

        /* Start/stop must consider the WHOLE frame, not just the last tick. `enabled`
           is a per-tick render flag; a note can be enabled in earlier ticks and gone
           by the last tick (a short/staccato note, or a release that completes
           mid-frame). Since only this function starts voices and it sampled one tick,
           those notes were dropped entirely. Use the most-recent enabled tick's sub
           for the params; if no tick is enabled, the note is off this frame. */
        NoteSubEu* sub = NULL;
        for (s32 t = ticks - 1; t >= 0; t--) {
            NoteSubEu* s = &gAudioCtx.noteSubsEu[t * stride + i];
            if (s->bitField0.enabled) { sub = s; break; }
        }
        if (sub == NULL) {
            if (v->active) voice_stop(i);
            continue;
        }

        u32 key;
        Resolved res;
        AramEntry* entry;
        if (!resolve(sub, &key, &res, &entry)) {
            if (v->active) voice_stop(i);
            continue;
        }

        u32 freq = calc_freq(sub, res.downsample_shift);
        u32 vol = calc_vol(sub);
        u32 pan = calc_pan(sub);

        int retrigger = (!v->active) || (v->sampleKey != key) || sub->bitField0.needsInit;

        if (retrigger) {
            if (v->active) voice_stop(i);          /* release old channel/sample */
            s32 ch = chan_alloc();
            if (ch < 0) { cache_release(entry); continue; }  /* no free channel */
            v->channel = ch;
            v->active = 1;
            v->sampleKey = key;
            v->entry = entry;
            v->downsampleShift = res.downsample_shift;
            chan_start(ch, &res, freq, vol, pan);
            v->sentFreq = freq; v->sentVol = (u8)vol; v->sentPan = (u8)pan;
#if AICA_OCTAVE_LOG
            /* Flag real ADPCM samples pitched past +1 octave (resampling ratio > 2.0;
               ratio = resamplingRateFixedPoint/32768, x2 if hasTwoParts). AICA ADPCM
               pitch-clamps there -> add `key` (src_offset) to FORCE_PCM_KEYS. One
               print per sample per new high; capped so it can't flood. */
            if (!sub->bitField1.isSyntheticWave && res.type == AICA_SM_ADPCM) {
                u32 rate = sub->resamplingRateFixedPoint;
                if (sub->bitField1.hasTwoParts) rate <<= 1;
                if (rate > 2u * 32768u) {
                    static u32 oKey[128]; static u32 oMax[128]; static s32 oN = 0;
                    s32 j, hit = -1;
                    for (j = 0; j < oN; j++) if (oKey[j] == key) { hit = j; break; }
                    if (hit < 0 && oN < 128) { hit = oN++; oKey[hit] = key; oMax[hit] = 0; }
                    if (hit >= 0 && rate > oMax[hit]) {
                        oMax[hit] = rate;
                        printf("OCTAVE key=%X ratio=%u.%03u\n", (unsigned)key,
                               (unsigned)(rate >> 15),
                               (unsigned)(((rate & 0x7FFFu) * 1000u) >> 15));
                    }
                }
            }
#endif
        } else {
            /* continuing note: release the extra ref taken by resolve() */
            if (entry != NULL) cache_release(entry);
            if (freq != v->sentFreq || (u8)vol != v->sentVol || (u8)pan != v->sentPan) {
                chan_update(v->channel, freq, vol, pan);
                v->sentFreq = freq; v->sentVol = (u8)vol; v->sentPan = (u8)pan;
            }
        }
    }
}

#else /* !__DREAMCAST__ */

const unsigned char* gAicaAdpcmPoolBase = 0;
void AicaSynth_Init(void) {}
void AicaSynth_Update(void) {}
void AicaSynth_RefreshActive(s32 tick) { (void)tick; }

#endif
